// C stdlib
#include <stdint.h>      // uint8_t, uint32_t
#include <string.h>      // memcpy
#include <stdio.h>       // printf
#include <errno.h>       // errno
#include <assert.h>      // assert

// POSIX / system (socket API, inet helpers, read/write, poll)
#include <sys/types.h>   // ssize_t
#include <unistd.h>      // read, write, close
#include <arpa/inet.h>   // htons, htonl, ntohs, inet_ntop
#include <netinet/in.h>  // sockaddr_in
#include <sys/socket.h>  // socket, bind, listen, accept, setsockopt
#include <poll.h>        // poll, struct pollfd

// C++ stdlib
#include <string>        // std::string
#include <vector>        // std::vector
#include <map>           // std::map

// local
#include "utils.h"
#include "constants.h"

static std::map<std::string, std::string> keyValueStore;

struct Connection {
    int socket_fd = -1; // listening/accepted socket fd, by default set to -1

    // application's intentions
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;

    // buffered input and output
    std::vector<uint8_t> incoming; // data to be parsed by the application
    std::vector<uint8_t> outgoing; // responses generated by the application
};

struct Response {
    uint32_t status;
    std::vector<uint8_t> data;
};

enum ResponseStatus {
    RES_OK = 200,
    RES_NX = 404,
    RES_ERR = 500,
};


/**
 * Handle the client connection
 */
static Connection *handle_accept(int listen_fd) {
    //accept the connection
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int conn_fd = accept(listen_fd, (struct sockaddr *)&client_addr, &addrlen);
    if (conn_fd < 0) { 
        msg_error("accept() error");
        return nullptr;
    }
    
    // get the client ip address, remember that IP is in little endian
    // eg: 192.168.1.100 is 0xc0a80164 in little endian
    // uint8_t byte0 = ip & 0xFF;           // 0xC0 = 192
    // uint8_t byte1 = (ip >> 8) & 0xFF;    // 0xA8 = 168
    // uint8_t byte2 = (ip >> 16) & 0xFF;   // 0x01 = 1
    // uint8_t byte3 = (ip >> 24) & 0xFF;   // 0x0A = 10
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "[server] accepted connection from %u.%u.%u.%u:%u\n", 
        ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, (ip >> 24), // moving 8 bits bcuz uint32_t is 4 bytes
        ntohs(client_addr.sin_port));

    // set the connection to non-blocking
    fd_set_nb(conn_fd);
    
    // create a new connection
    Connection *conn = new Connection();
    conn->socket_fd = conn_fd;
    conn->want_read = true;
    return conn;
}

/**
 * Read the header for the request (size or total number of requests)
 */
static bool read_header(const uint8_t *&cursor, const uint8_t *end, uint32_t &value) {
    // Check if there is enough data to read the header`
    if (end - cursor < 4) { return false; }

    // Read the header, move the pointer to the next 4 bytes
    memcpy(&value, cursor, 4);
    cursor += 4;
    
    return true;
}

/**
 * Read the request
 */
static bool read_string(const uint8_t *&cursor, const uint8_t *end, uint32_t len, std::string &output) {
    // Check if there is enough data to read the string
    if (end - cursor < len) { return false; }

    // Read the string, move the pointer to the next len bytes
    output = std::string((char*)cursor, len);
    cursor += len;

    return true;
}

/** 
 * Parse one request:
 *      +----------+-----+------+-----+------+-----+-----+------+
 *      | num_args | len | cmd1 | len | cmd2 | ... | len | cmdn |
 *      +----------+-----+------+-----+------+-----+-----+------+
 */
static int32_t parse_request(const uint8_t *data, size_t size, std::vector<std::string> &cmd) {
    const uint8_t *cursor = data;
    const uint8_t *end = cursor + size;
    uint32_t num_args = 0;

    // Read the request header
    if (!read_header(cursor, end , num_args)) { return -1; } // Read the total number of requests
    if (num_args > k_max_args) { return -1; }

    // Read the requests
    while (cmd.size() < num_args) {
        uint32_t len = 0;

        // Read the length of the request
        if (!read_header(cursor, end , len)) { return -1; }

        cmd.push_back(std::string()); // push back an empty string

        // Read the request
        if (!read_string(cursor, end, len, cmd.back())) { return -1; }
    }

    // Check if there is any remaining data
    if (cursor != end) { return -1; }

    return 0;
}

/** 
 * Run one request
 */
static void run_request(std::vector<std::string> &cmd, Response &resp) {
    // PING request
    if (cmd.size() == 1 && cmd[0] == "PING") {
        const uint8_t *p = (const uint8_t*)"PONG";
        resp.data.assign(p, p + 4);
    }

    // GET request
    else if (cmd.size() == 2 && cmd[0] == "GET") {
        auto it = keyValueStore.find(cmd[1]);
        if (it == keyValueStore.end()) {
            resp.status = RES_NX;        // Not Found command
            return;
        }
        const std::string &value = it->second;
        resp.data.assign(value.begin(), value.end());
    }

    // SET request
    else if (cmd.size() == 3 && cmd[0] == "SET") {
        keyValueStore[cmd[1]].swap(cmd[2]);    // swap the value of the key
    }

    // DEL request
    else if (cmd.size() == 2 && cmd[0] == "DEL") {
        keyValueStore.erase(cmd[1]);
    }

    // ALL_KEYS request
    else if (cmd.size() == 1 && cmd[0] == "ALL_KEYS") {
        for (const auto &entry : keyValueStore) {
            const std::string &key = entry.first;
            resp.data.insert(resp.data.end(), key.begin(), key.end());
            resp.data.push_back('\n');
        }
    }

    // Unknown request
    else {
        resp.status = RES_ERR;        // Unknown command
        return;
    }

    resp.status = RES_OK;        // OK command
}

/**
 * Generate the response
 */
static void generate_response(const Response &resp, std::vector<uint8_t> &out) {
    // 4 bytes for the status code + the size of the data
    uint32_t resp_len = 4 + (uint32_t)resp.data.size();

    // append the length of the response
    append_buffer(out, (const uint8_t*)&resp_len, 4);

    // append the status code
    append_buffer(out, (const uint8_t*)&resp.status, 4);

    // append the data
    append_buffer(out, resp.data.data(), resp.data.size());
}

/**
 * Process one request when there is enough data
 */
static bool handle_one_request(Connection *conn) {
    // try to parse the protocol: message header
    if (conn->incoming.size() < 4) { return false; } // we don't even know the size of the message

    uint32_t frame_len = 0;
    memcpy(&frame_len, conn->incoming.data(), 4);
    if (frame_len > k_max_msg) {
        msg_error("too long");
        conn->want_close = true;
        return false;
    }
    
    // Get the message payload
    if (4 + frame_len > conn->incoming.size()) { return false; } // size of the payload is incorrect
    const uint8_t *request = conn->incoming.data() + 4;

    // Parse the request and apply application logic
    std::vector<std::string> cmd;
    if (parse_request(request, frame_len, cmd) < 0) {
        conn->want_close = true;
        return false;
    }

    Response resp;
    // Run the request
    run_request(cmd, resp);
    // Generate the response
    generate_response(resp, conn->outgoing);
    // Consume the incoming data
    consume_buffer(conn->incoming, 4 + frame_len);
    return true;
}

/**
 * Application callback when the socket is writable
 */
static void handle_write(Connection *conn) {
    assert(!conn->outgoing.empty()); // check if there is any outgoing data

    // write the response to the socket, outgoing[0] is the pointer to the buffer
    ssize_t rv = write(conn->socket_fd, &conn->outgoing[0], conn->outgoing.size());
    if (rv < 0) {
        if (errno == EAGAIN) { return; } // actually not ready to write as the buffer is full

        msg_error("write() error"); // write() error
        conn->want_close = true;
        return;
    }

    // remove the written data from the outgoing buffer
    consume_buffer(conn->outgoing, (size_t)rv);

    // update the readiness flag
    if (conn->outgoing.size() == 0) { // if there is no outgoing data, we want to read
        conn->want_read = true;
        conn->want_write = false;
    }
}   

/**
 * Application callback when the socket is readable
 * Read the request and parse it
 * Generate the response
 * Write the response to the socket
 */
static void handle_read(Connection *conn) {
    // read the request [4b header + payload]
    uint8_t buf[64 * 1024]; // 64KB buffer
    ssize_t rv = read(conn->socket_fd, buf, sizeof(buf));
    if (rv < 0) {
        if (errno == EAGAIN) { return; } // actually not ready

        // handle IO errors
        msg_error("read() error");
        conn->want_close = true;
        return; // want to close the connection
    }

    // Handle EOF, closing as we are done with the connection
    if (rv == 0) {
        if (conn->incoming.empty()) { msg("[server] client closed connection"); }
        else { msg("unexpected EOF"); }
        conn->want_close = true;
        return;
    }
    
    // append the incoming data to the buffer
    append_buffer(conn->incoming, buf, (size_t)rv);

    // parse the request and generate response, in a while loop as there may be multiple requests in the buffer
    while (handle_one_request(conn)) {}

    // update the readiness flag
    if (!conn->outgoing.empty()) { // if there is outgoing data, we want to write
        conn->want_read = false;
        conn->want_write = true;

        // The socket is likely ready to write in a request-response protocol,
        // try to write it without waiting for the next iteration.
        return handle_write(conn);
    }
}

/**
 * Main function
 * 
 * Initializes a TCP server that listens on port 8080 for incoming client connections.
 * - Creates a non-blocking listening socket bound to 0.0.0.0:8080.
 * - Uses poll() to multiplex I/O across multiple client connections.
 * - Accepts new connections and tracks them using a vector indexed by file descriptor.
 * - Handles readable and writable events for each client socket.
 * - Cleans up connections on error or when marked for closure.
 * 
 * This function runs an infinite event loop and only exits on fatal error.
 * 
 * Return 0 on successful execution.
 */
int main() {
    // the listening socket
    int listen_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (listen_fd < 0) { die("socket()"); }
    msg("[server] socket created");

    int val = 1;
    setsockopt(listen_fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val)); // set the port to reusable when the program is restarted

    // declare the socket connection
    struct sockaddr_in addr ={};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(8080);  //port
    addr.sin_addr.s_addr = htonl(0); //wildcard ip 0.0.0.0    INADDR_ANY; // listen to all addresses

    // bind
    int rv = bind(listen_fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv) { die("bind()"); } 
    msg("[server] bind successful on 0.0.0.0:8080");

    // set the listen fd to nonblocking mode
    fd_set_nb(listen_fd);

    // listen
    rv = listen(listen_fd, SOMAXCONN);
    if (rv) {die("listen()");} 
    msg("[server] listen successful on 0.0.0.0:8080");

    // a map of all the client connections, keyed by the file descriptor
    std::vector<Connection *> fd2conn;
    
    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true) {
        // prepare the arguments for the poll()
        poll_args.clear();

        // put the listening socket into the poll_args in the first position
    struct pollfd pfd = {listen_fd, POLLIN, 0};
        poll_args.push_back(pfd);

        // the rest are the connection sockets
        for (Connection *conn : fd2conn) {
            if (!conn) { continue; }

            // always poll() for errors
            struct pollfd pfd = {conn->socket_fd, POLLERR, 0};
            if (conn->want_read) { pfd.events |= POLLIN; } // if we want to read, add POLLIN to the events
            if (conn->want_write) { pfd.events |= POLLOUT; } // if we want to write, add POLLOUT to the events
            poll_args.push_back(pfd);
        }

        // poll() for events, polling for readiness
        rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if (rv < 0) { 
            if (errno == EINTR) { continue; }
            die("poll()"); 
        }
        
        // handle the listening socket, poll_args[0] is the listening socket
        // revents is the events that happened on the socket
        if (poll_args[0].revents) {
            if (Connection *conn = handle_accept(listen_fd)) {
                // put it in the map
                if (fd2conn.size() <= (size_t) conn->socket_fd) { fd2conn.resize(conn->socket_fd + 1); }
                
                // put it in the map
                assert(!fd2conn[conn->socket_fd]);
                fd2conn[conn->socket_fd] = conn;
                // here the mapping is the position being same as the file descriptor
            }
        }

        // handle the client connections sockets
        for (size_t i = 1; i < poll_args.size(); i++) { // skipping the first, as we put it there
            uint32_t ready = poll_args[i].revents;
            if (ready == 0) { continue; }

            // get the connection
            Connection *conn = fd2conn[poll_args[i].fd];
            
            if ((ready & POLLIN) && conn->want_read)  { handle_read(conn); }
            if ((ready & POLLOUT) && conn->want_write) { handle_write(conn); }

            if ((ready & POLLERR) || conn->want_close) {
                (void)close(conn->socket_fd);
                fd2conn[conn->socket_fd] = NULL;
                delete conn;
            }
        }
        // for each connection socket
    }
    // for event loop
    return 0;
}